### PR TITLE
# for android API 28

### PR DESCRIPTION
**Pull request by dotkebi**
# update for API 28

* apply `androidx.appcompat`
* apply `com.google.android.material`

### CODE REVIEW

**Comment by pwittchen** [comment]
Hi @dotkebi. Thanks for creating this PR!
Could you update `.travis.yml` and `library/build.gradle` file with the correct versions and packages too to make Travis CI build pass? Now, it's failing.

**Comment by dotkebi** [comment]
Dear @pwittchen ,
I'm not good at `travis` and `checkstyle`.
`Checkstyle` occurs some error, but I can't find solutions.
[Unable to crate a Checker {} classpath {null}](https://www.google.co.kr/search?q=Unable+to+create+a+Checker%3A+configLocation+%7B%7D%2C+classpath+%7Bnull%7D.&oq=Unable+to+create+a+Checker%3A+configLocation+%7B%7D%2C+classpath+%7Bnull%7D.&aqs=chrome..69i57.486j0j7&sourceid=chrome&ie=UTF-8)

**Comment by pwittchen** [comment]
Please reformat code with the project code style (https://github.com/pwittchen/InfiniteScroll#code-style) and it should fine.

**Comment by pwittchen** [comment]
Thanks for your patience!

**Pull request merged**
